export const ACTIVITIES = [
  {
    id: "1",
    title: "Parachute Drop Challenge",
    category: "Engineering",
    desc: "Design and test parachutes to reduce landing speed",
    icon: "rocket-outline",
    routeName: "ParachuteChallenge/parachute",
  },
  {
    id: "2",
    title: "Sound Pollution Hunter",
    category: "Environmental Science",
    desc: "Measure and compare sound levels in different activities",
    icon: "options-outline",
    routeName: "SoundPollutionHunter/sound",
  },
  {
    id: "3",
    title: "Hand Fan Challenge",
    category: "Physics",
    desc: "Test how air movement affects flexible materials",
    icon: "color-wand-outline",
    routeName: "HandFanChallenge/handfan",
  },
  {
    id: "4",
    title: "Human Performance Lab",
    category: "Medical Science",
    desc: "Measure speed, smoothness, and coordination",
    icon: "pulse-outline",
    routeName: "HumanPerformanceChallenge/humanperformance",
  },
  {
    id: "5",
    title: "Reaction Board Challenge",
    category: "Neuroscience",
    desc: "Measure reaction time and coordination",
    icon: "timer-outline",
    routeName: "ReactionChallenge/reaction",
  },
  {
    id: "6",
    title: "Earthquake Challenge",
    category: "Engineering",
    desc: "Design structures to withstand simulated earthquakes",
    icon: "construct-outline",
    routeName: "EarthquakeChallenge/earthquake",
  },
];
